version: '3'

services:

  traefik:
    image: "traefik:latest"
    restart: "unless-stopped"
    container_name: "traefik"
    command: ["--configfile=/traefik.toml"]
    ports:
      - "80:80"
      - "443:443"
    links:
      - "frontend"
      - "backend"
    volumes:
      - "/deep-shirt/confs/traefik.toml:/traefik.toml:ro"
      - "/deep-shirt/letsencrypt/certs:/certs:ro"
      - "/etc/localtime:/etc/localtime:ro"
    network_mode: "bridge"

  frontend:
    image: "nginx:alpine"
    restart: "unless-stopped"
    container_name: "frontend"
    hostname: "frontend"
    volumes:
      - "/deep-shirt/confs/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/deep-shirt/confs/server.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/deep-shirt/www:/usr/share/nginx/html:ro"
      - "/etc/localtime:/etc/localtime:ro"
    network_mode: "bridge"

  backend:
    image: "deepshirt/backend:latest"
    restart: "unless-stopped"
    container_name: "backend"
    hostname: "backend"
    volumes:
      - "/deep-shirt/keys/firebase-service-account.json:/firebase-service-account.json:ro"
    env_file:
      - "/deep-shirt/envs/backend.env"
    network_mode: "bridge"
